# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SilkRoad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SilkRoad
    pod 'SnapKit' #用于UI布局
    pod 'Alamofire' #网络请求
    pod 'Eureka'
    
end
